# #############################  Extracted using PyRadiomics version: <version>  ######################################

imageType:
  Original: {}
  LoG:
    # If the in-plane spacing is large (> 2mm), consider removing sigma value 1.
    sigma: [1.0, 3.0, 5.0]
  Wavelet: {}

featureClass:
  # redundant Compactness 1, Compactness 2 an Spherical Disproportion features are disabled by default, they can be
  # enabled by specifying individual feature names (as is done for glcm) and including them in the list.
  shape:
  firstorder:
  glcm:
  glrlm:
  glszm:
  gldm:
  ngtdm:

setting:
  # Normalization:
  # MR signal is usually relative, with large differences between scanners and vendors. By normalizing the image before
  # feature calculation, this confounding effect may be reduced. However, if only one specific scanner is used, or the
  # images reflect some absolute world value (e.g. ADC maps, T2maps (NOT T2 weighted)), consider disabling the
  # normalization.
  normalize: true
  normalizeScale: 100  # This allows you to use more or less the same bin width.

  # Resampling:
  # Not enabled in this example. However, because texture calculation assumes isotropic spacing, a forced 2D extraction
  # is used, therefore only requiring the voxels to be isotropic in-plane. Enable pre-cropping to reduce memory
  # footprint and speed up applying the filters.
  preCrop: true

  # Minimum ROI label size (voxel count)
  minimumROISize: 10

  binWidth: 5
  # first order specific settings:
  # When normalizing, gray values below the mean will be negative. Shifting by 300 (3 StdDevs * 100) ensures that the
  # majority of voxels is positive (only outliers >3 SD lower than the mean will be negative).
  voxelArrayShift: 300
